------------------------------------------------------------
-- STEP 1: XÓA TOÀN BỘ CÁC BẢNG (KÈM KHÓA NGOẠI)
------------------------------------------------------------
-- Thêm CASCADE CONSTRAINTS để Oracle tự động cắt đứt các quan hệ FK nối giữa các bảng
DROP TABLE HOANTRA CASCADE CONSTRAINTS;
DROP TABLE HOADONHOCPHI CASCADE CONSTRAINTS;
DROP TABLE HOCBONG CASCADE CONSTRAINTS;
DROP TABLE YEUCAUCHUYENLOP CASCADE CONSTRAINTS;
DROP TABLE DANGKY CASCADE CONSTRAINTS;
DROP TABLE TAILIEU CASCADE CONSTRAINTS;
DROP TABLE THAMGIABKT CASCADE CONSTRAINTS;
DROP TABLE BAIKIEMTRA CASCADE CONSTRAINTS;
DROP TABLE DIEMDANH CASCADE CONSTRAINTS;
DROP TABLE BUOIHOC CASCADE CONSTRAINTS;
DROP TABLE LICHHOC CASCADE CONSTRAINTS;
DROP TABLE LOPHOC CASCADE CONSTRAINTS;
DROP TABLE KHOAHOC CASCADE CONSTRAINTS;
DROP TABLE BOMON CASCADE CONSTRAINTS;
DROP TABLE GIAOVIEN CASCADE CONSTRAINTS;
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;
DROP TABLE HOCVIEN CASCADE CONSTRAINTS;
DROP TABLE TAIKHOAN CASCADE CONSTRAINTS;
DROP TABLE VAITRO CASCADE CONSTRAINTS;
DROP TABLE PHONGHOC CASCADE CONSTRAINTS;
DROP TABLE NGAYNGHILE CASCADE CONSTRAINTS;

DROP TABLE GIAMGIA CASCADE CONSTRAINTS;
DROP TABLE NHATKYHETHONG CASCADE CONSTRAINTS;
DROP TABLE THONGTINNGANHANG CASCADE CONSTRAINTS;


------------------------------------------------------------
-- STEP 2: XÓA CÁC STORED PROCEDURE ĐỘC LẬP
------------------------------------------------------------
DROP PROCEDURE sp_KhoiTaoLopHoc;
DROP PROCEDURE sp_TaoHoaDonHocPhi;
DROP PROCEDURE sp_DuyetChuyenLop;
DROP PROCEDURE sp_DiemDanhBulk;
DROP PROCEDURE sp_HuyBuoiHocBaoBu;
DROP PROCEDURE sp_ChotDoanhThuThang;
DROP PROCEDURE sp_XuLyHoanTra;

-- Thông báo dọn dẹp hoàn tất (Nếu chạy trên SQL Plus / SQL Developer)
PURGE RECYCLEBIN;