------------------------------------------------------------
-- SCRIPT LÀM SẠCH VÀ PHÁ HỦY TOÀN BỘ DATABASE SCHEMA
------------------------------------------------------------
-- 1. ÉP XÓA BẢNG VÀ TỰ ĐỘNG BẺ KHÓA NGOẠI (CASCADE CONSTRAINTS)
DROP TABLE HOANTRA CASCADE CONSTRAINTS;
DROP TABLE HOADONHOCPHI CASCADE CONSTRAINTS;
DROP TABLE HOCBONG CASCADE CONSTRAINTS;
DROP TABLE YEUCAUCHUYENLOP CASCADE CONSTRAINTS;
DROP TABLE DANGKY CASCADE CONSTRAINTS;
DROP TABLE TAILIEU CASCADE CONSTRAINTS;
DROP TABLE THAMGIABKT CASCADE CONSTRAINTS;
DROP TABLE BAIKIEMTRA CASCADE CONSTRAINTS;
DROP TABLE DIEMDANH CASCADE CONSTRAINTS;
DROP TABLE BUOIHOC CASCADE CONSTRAINTS;
DROP TABLE LICHHOC CASCADE CONSTRAINTS;
DROP TABLE LOPHOC CASCADE CONSTRAINTS;
DROP TABLE KHOAHOC CASCADE CONSTRAINTS;
DROP TABLE BOMON CASCADE CONSTRAINTS;
DROP TABLE GIAOVIEN CASCADE CONSTRAINTS;
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;
DROP TABLE HOCVIEN CASCADE CONSTRAINTS;
DROP TABLE TAIKHOAN CASCADE CONSTRAINTS;
DROP TABLE VAITRO CASCADE CONSTRAINTS;
DROP TABLE PHONGHOC CASCADE CONSTRAINTS;
DROP TABLE NGAYNGHILE CASCADE CONSTRAINTS;
DROP TABLE GIAMGIA CASCADE CONSTRAINTS;
DROP TABLE NHATKYHETHONG CASCADE CONSTRAINTS;
DROP TABLE THONGTINNGANHANG CASCADE CONSTRAINTS;

-- 2. XÓA CÁC PROCEDURES
DROP PROCEDURE SP_ENROLL_STUDENT;
DROP PROCEDURE SP_EXECUTE_CLASS_TRANSFER;
DROP PROCEDURE SP_ANALYZE_ABSENCE_ALERT;
DROP PROCEDURE SP_PROCESS_PAYMENT;
DROP PROCEDURE SP_PROCESS_REFUND;

-- 3. GIẢI PHÓNG BỘ NHỚ ĐỆM CỦA ORACLE
PURGE RECYCLEBIN;